### ISSUE TITLE
how can i run the js file

### ISSUE THREAD

**Issue by virginsince1997** [chrisjluc/Photoliker#1]
hello thanks for your script but how can i run this script on android and s it possible to run on android

**Comment by chrisjluc** [comment]
Hey, I never tried running it on android. I've only done this on the browser with phantom js.

**Comment by virginsince1997** [comment]
Okay, Thanks for replying, Please does it still work?

**Comment by virginsince1997** [comment]
And Can you give me your email ID like to ask you some few questions,
Thanks

**Comment by chrisjluc** [comment]
There were some issues with not being able to like photos consistently, its kind of sporadic.
chris.luc93@gmail.com
